### ISSUE TITLE
Error when ending combat

### ISSUE THREAD

**Issue by Kayne** [jsavko/pf2e-award-xp#12]
Using pf2e 5.7.3 and fvtt 11.315 Stable.

When ending combat this exception raises in console:
```
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'preDeleteCombat'. Cannot read properties of undefined (reading 'variants')
    at Object.fn (pf2e-awardxp.js:13:37)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at #preDeleteDocumentArray (foundry.js:13776:44)
    at async _ClientDatabaseBackendPF2e._deleteDocuments (foundry.js:13472:22)
```

**Comment by jsavko** [comment]
Update your PF2E install. You are seriously out of date.

**Comment by Kayne** [comment]
Yeah. I can't update since it forces using remaster rules in latest system version :(
But that's what I figured out. I ruled out other modules, so maybe it's pf2e system version difference. Thanks anyway!

**Comment by jsavko** [comment]
This module was made after the remaster rules were implemented and has no intention of supporting old versions of the pf2e system.   Since the module uses the party system and other system specific features that came with the remaster there isn't much to do.   
I suggest installing the oldest version of this module as it may work with pre-remaster rules
